### ISSUE TITLE
Missing implementations required for analysis functions

### ISSUE THREAD

**Issue by yimuchen** [dask-contrib/dask-awkward#214]
Slowly trying to port our analysis code to be compatible with `dask_awkward`. There are some function that we ran into the NotImplemented error when processing some triple-nested array.

```python
import awkward as ak
import dask_awkward as dak
import numpy as np

# Making a triply nested array
arr = ak.from_regular(np.random.random(size=(10, 10, 10)))
arr = dak.from_awkward(arr, npartitions=1)

# print(arr[..., 0:5]) # Array.__getitem__ doesn't support multi object: (Ellipsis, slice(0, 5, None))
# print(dak.argmin(arr,axis=-2)) # axis=-2 is a TODO
# print(dak.any(arr > 0.5, axis=None)) # axis=None is a TODO
```

- [x] `__getitem__` with Ellipsis as first arg (#217)
- [x] `argmin`/`argmax` negative `axis` argument (#267)
- [x] `any` `axis=None` (#267)

**Comment by douglasdavis** [comment]
Thanks for raising! We'll start working working on these implementations.

**Comment by agoose77** [comment]
> argmin / argmax with negative axis

Is covered by #267!

**Comment by douglasdavis** [comment]
looks like this should be good, please re-open if not!
